feature1
yuta-nakaa/customers pull request #1
Opened 2021-06-23 21:13 UTC by yuta-nakaa

遅くなり申し訳ございません。
登録画面のエラーメッセージのとこで詰まってしまいました。
一度提出いたします。
よろしくお願いします！

2021-06-23 21:38 UTC, kazu-taka requested changes
@yuta-nakaa 
全体的にコードが綺麗で見やすいです✨
いくつかコメントしたので確認お願いします:bow:

2021-06-23 21:38 UTC, kazu-taka commented on new.php
> +    }
@yuta-nakaa 
登録処理が途中なのでここで`$errors`が空の時に、SQLのINSERT文を使用してcustomersテーブルに登録するようにお願いします!

2021-06-23 21:38 UTC, kazu-taka commented on new.php
> +
@yuta-nakaa 
`insertValidate`という関数が`functions.php`に存在しないので、追加して下さい！
`insertValidate`関数は、引数を3つ($companay、$name、$email)受け取るようにして、一気に3つの項目をチェックするようにして下さい✨

2021-06-23 21:38 UTC, kazu-taka commented on new.php
> +                <input type="submit" class="btn submit-btn" value="追加">
@yuta-nakaa 
バリデーションでエラーとなった場合、入力した内容が消えてしまうので、inputタグにvalue属性を指定して、フォームで入力した内容($companyや$email)をセットするようにして下さい✨

2021-06-23 21:38 UTC, kazu-taka commented on index.php
> +$customers_info = getCustomerInfo();
@yuta-nakaa 
関数にしてるのはいいですね✨
ここは`getCuntomers`(複数のデータを取得するため)の方がいいと思います👍

2021-06-23 21:38 UTC, kazu-taka commented on functions.php
> +    EMO;
@yuta-nakaa 
`EMO`でも問題ないですが、`End Of Message`の略で、`EOM`の方がいいと思います✨

2021-06-24 22:54 UTC, yuta-nakaa commented
お疲れ様です。

一度修正したのですがエラーメッセージ出ないのですがよくわかりません。。
ご教授願います。

2021-06-25 13:45 UTC, yuta-nakaa commented
@kazu-taka お疲れ様です。

一度修正したのですがエラーメッセージ出ないのですがよくわかりません
ご教授願います🙇‍♂️

2021-06-25 13:53 UTC, kazu-taka requested changes
@yuta-nakaa 
コメントしたので確認お願いします:bow:

2021-06-25 13:53 UTC, kazu-taka commented on new.php
> +    $errors = insertValidate($company,$name,$email);
@yuta-nakaa 
insertValidateという関数が存在しないのでエラーになっていると思われます！
functions.phpにinsertValidate関数を作成し、その関数内に以下の処理を入れるようにして下さい✨
以下のコード+もう少し処理が必要になります！
```php
    if ($company == '') {
        $errors[] = '会社名を入力してください';
    }
    if ($name == '') {
        $errors[] = '氏名を入力してください';
    }
    if ($email == '') {
        $errors[] = 'メールアドレスを入力してください';
    }
```

2021-06-26 09:48 UTC, yuta-nakaa commented
@kazu-taka 何度も申し訳ございません。
functions.phpに追加したのですが
変わりません。
どうすればよいのでしょうか？🙇‍♂️

2021-06-26 10:54 UTC, Arisaarisa reviewed
課題提出お疲れさまです！
関数定義できるものはfunctions.phpに一旦整理してみましょう:relaxed:

2021-06-26 10:54 UTC, Arisaarisa commented on functions.php
> +        $errors[] = '会社名を入力してください';
`会社名を入力してください`の部分は`config.php`で定数定義をし、
`$errors[]`には定数名で渡してあげるようにしてみてください:blush:
以下2つも同じように定数にします！

2021-06-26 10:54 UTC, Arisaarisa commented on new.php
> +    if ($company == '') {
functions.phpにinsertValidate関数の定義はしているのでここでは`バリデーション`の中でinsert用の関数の$company, $name, $emailのチェックを書きます:sparkles:

なので`function.php`にinsert用の関数を用意しデータベースに接続し、INSERTするようにしてみましょう！

2021-06-26 11:20 UTC, kazu-taka commented on functions.php
> +}
@yuta-nakaa 
ifの{に対する}のインデントの修正をお願いします:bow:

2021-06-26 11:23 UTC, kazu-taka commented on new.php
> +        $stmt = $dbh->prepare($sql);
@yuta-nakaa 
$dbhを使用していますが、`$dbh = connectDb();`を実行していないので、ここでエラーになります^^;

2021-06-27 07:50 UTC, kazu-taka commented on functions.php
> +}
@yuta-nakaa 
めちゃめちゃ細かくてすみません^^;
ifの{と}の位置がずれているので、修正お願いします！！」
```php
    if ($name  == '') {
        $errors[] = '氏名を入力してください';
}
```

2021-06-27 07:51 UTC, kazu-taka commented on functions.php
> +}
@yuta-nakaa 
この関数は使われていないので、削除お願いします:bow:

2021-06-27 07:51 UTC, kazu-taka commented on index.php
> +
@yuta-nakaa 
ここの空行は削除お願いします:bow:

2021-06-27 08:13 UTC, kazu-taka commented on edit.php
> +            <ul class="errors">
@yuta-nakaa 
次の課題の内容ですが、ulタグはif文の中にあるので、ここは削除してOKです！！

2021-07-10 05:43 UTC, merged